//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralService.Core.Statistics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A002
    {
        public int depcode { get; set; }
        public string depname { get; set; }
        public string depin { get; set; }
        public string deptype { get; set; }
        public string leader { get; set; }
        public string viceleader { get; set; }
        public string Tel { get; set; }
        public bool isinuse { get; set; }
        public string des { get; set; }
        public string OnEditor { get; set; }
        public Nullable<System.DateTime> OnDate { get; set; }
        public string Editor { get; set; }
        public Nullable<System.DateTime> EditTime { get; set; }
        public string auditor { get; set; }
        public Nullable<System.DateTime> audittime { get; set; }
        public Nullable<bool> isdel { get; set; }
        public byte[] tsp { get; set; }
    }
}
