//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralService.Core.Statistics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A004
    {
        public long csid { get; set; }
        public string cssort { get; set; }
        public string csvalue { get; set; }
        public string csname { get; set; }
        public string paramvalue { get; set; }
        public string des { get; set; }
        public Nullable<bool> isinuse { get; set; }
        public Nullable<System.DateTime> ondate { get; set; }
        public string editor { get; set; }
        public Nullable<System.DateTime> edittime { get; set; }
        public string auditor { get; set; }
        public Nullable<System.DateTime> audittime { get; set; }
        public string oneditor { get; set; }
        public Nullable<bool> isdel { get; set; }
        public Nullable<int> depcode { get; set; }
    }
}
