//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralService.Core.Statistics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A006
    {
        public int id { get; set; }
        public int partid { get; set; }
        public int menuid { get; set; }
        public int qx { get; set; }
        public Nullable<int> PanelBTOrder { get; set; }
        public Nullable<bool> IsBTInPanel { get; set; }
    }
}
