//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralService.Core.Statistics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A022
    {
        public string NeedCodeObjectName { get; set; }
        public string TableName { get; set; }
        public string NeedCodeFieldName { get; set; }
        public string prefix { get; set; }
        public string datefix { get; set; }
        public string postfix { get; set; }
        public string outareafix { get; set; }
        public string CodeOrderType { get; set; }
        public string filtercondition { get; set; }
        public Nullable<bool> isinuse { get; set; }
        public byte[] tsp { get; set; }
        public string des { get; set; }
        public Nullable<System.DateTime> ondate { get; set; }
        public string editor { get; set; }
        public Nullable<System.DateTime> edittime { get; set; }
        public string auditor { get; set; }
        public Nullable<System.DateTime> audittime { get; set; }
        public bool isdel { get; set; }
    }
}
