//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralService.Core.Statistics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A030UnitBase
    {
        public int id { get; set; }
        public string u_account { get; set; }
        public string u_name { get; set; }
        public string u_quality { get; set; }
        public string u_type { get; set; }
        public Nullable<int> status { get; set; }
        public string officephone { get; set; }
        public string officeaddress { get; set; }
        public string e_mail { get; set; }
        public string website { get; set; }
        public string og_code_id { get; set; }
        public string number_id { get; set; }
        public string fund_type { get; set; }
        public string bank_for_unit { get; set; }
        public Nullable<System.DateTime> bank_open_date { get; set; }
        public string area_code { get; set; }
        public string bank_card { get; set; }
        public string economy_type { get; set; }
        public string belong_type { get; set; }
        public string charge_unit_name { get; set; }
        public string principal { get; set; }
        public string principal_phone { get; set; }
        public string principal_id_type { get; set; }
        public string principal_id_no { get; set; }
        public string principal_mobile_phone { get; set; }
        public string charge_unit_principal { get; set; }
        public string charge_unit_principal_phone { get; set; }
        public string approval_unit { get; set; }
        public string approval_document { get; set; }
        public string leagal_person_name { get; set; }
        public string leagal_person_cert_type { get; set; }
        public string leagal_person_cert_num { get; set; }
        public string leagal_person_phone { get; set; }
        public string leagal_person_mobile_phone { get; set; }
        public string leagal_person_email { get; set; }
        public Nullable<decimal> u_bili { get; set; }
        public Nullable<System.DateTime> jiaocun_create_date { get; set; }
        public Nullable<System.DateTime> jiaocun_begin_date { get; set; }
        public string liushuihao { get; set; }
        public Nullable<int> SendCount { get; set; }
        public string renderNo { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public Nullable<System.DateTime> finishdate { get; set; }
        public byte[] tsp { get; set; }
        public Nullable<System.DateTime> ondate { get; set; }
        public string editor { get; set; }
        public string des { get; set; }
        public Nullable<System.DateTime> edittime { get; set; }
        public string auditor { get; set; }
        public Nullable<System.DateTime> audittime { get; set; }
        public bool isdel { get; set; }
        public Nullable<int> print_tag { get; set; }
        public Nullable<bool> isPrint { get; set; }
    }
}
