//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralService.Core.Statistics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A033PreFetch
    {
        public int id { get; set; }
        public string responsNum { get; set; }
        public Nullable<int> areaCode { get; set; }
        public Nullable<int> aId { get; set; }
        public Nullable<int> uId { get; set; }
        public string account { get; set; }
        public string idCard { get; set; }
        public string tel { get; set; }
        public string fetchType { get; set; }
        public Nullable<decimal> fetchMoney { get; set; }
        public string status { get; set; }
        public string filePath { get; set; }
        public byte[] tsp { get; set; }
        public Nullable<System.DateTime> ondate { get; set; }
        public string editor { get; set; }
        public string des { get; set; }
        public Nullable<System.DateTime> edittime { get; set; }
        public string auditor { get; set; }
        public Nullable<System.DateTime> audittime { get; set; }
        public bool isdel { get; set; }
    }
}
