//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralService.Core.Statistics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A040LoanFileInfo
    {
        public string queryId { get; set; }
        public Nullable<int> depCode { get; set; }
        public Nullable<int> bankId { get; set; }
        public string bankName { get; set; }
        public string loanName { get; set; }
        public string loanIdcard { get; set; }
        public string address { get; set; }
        public int currentStep { get; set; }
        public string remark { get; set; }
        public string loanTel { get; set; }
        public string bankTel { get; set; }
        public string LandTel { get; set; }
        public Nullable<System.DateTime> ondate { get; set; }
        public string editor { get; set; }
        public string des { get; set; }
        public Nullable<System.DateTime> edittime { get; set; }
        public string auditor { get; set; }
        public Nullable<System.DateTime> audittime { get; set; }
        public bool isdel { get; set; }
        public byte[] tsp { get; set; }
    }
}
