//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralService.Core.Statistics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A040LoanFileInfo_1
    {
        public int mxid { get; set; }
        public string queryId { get; set; }
        public int step { get; set; }
        public System.DateTime jjDate { get; set; }
        public string rejectDes { get; set; }
        public Nullable<System.DateTime> ondate { get; set; }
        public string editor { get; set; }
        public byte[] tsp { get; set; }
    }
}
