//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralService.Core.Statistics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingLog
    {
        public int id { get; set; }
        public string type { get; set; }
        public string @interface { get; set; }
        public System.DateTime time { get; set; }
        public string description { get; set; }
    }
}
