//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralService.Core.Statistics.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GjjBookingEntities : DbContext
    {
        public GjjBookingEntities()
            : base("name=GjjBookingEntities")
        {
            //System.Console.WriteLine(Database.Connection.ConnectionString);
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BlackList> BlackList { get; set; }
        public virtual DbSet<BookingLeft> BookingLeft { get; set; }
        public virtual DbSet<BookingLog> BookingLog { get; set; }
        public virtual DbSet<BookingRecord> BookingRecord { get; set; }
        public virtual DbSet<BookingSet> BookingSet { get; set; }
        public virtual DbSet<BusinessInfo> BusinessInfo { get; set; }
        public virtual DbSet<Managers> Managers { get; set; }
        public virtual DbSet<SpecialDay> SpecialDay { get; set; }
    }
}
