//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralService.Core.Statistics.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JmgjjPreliminaryEntities : DbContext
    {
        public JmgjjPreliminaryEntities()
            : base("name=JmgjjPreliminaryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<A030PreUnit> A030PreUnit { get; set; }
        public virtual DbSet<A033PreFetch> A033PreFetch { get; set; }
        public virtual DbSet<A034preAccount> A034preAccount { get; set; }
        public virtual DbSet<A035preLockAndUnLock> A035preLockAndUnLock { get; set; }
        public virtual DbSet<A036preBuJiao> A036preBuJiao { get; set; }
        public virtual DbSet<A037preJctz> A037preJctz { get; set; }
        public virtual DbSet<A038TranIn> A038TranIn { get; set; }
    }
}
