//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralService.Core.Statistics.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JMGJJFactEntities : DbContext
    {
        public JMGJJFactEntities()
            : base("name=JMGJJFactEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_account> t_account { get; set; }
        public virtual DbSet<t_account_autofetch> t_account_autofetch { get; set; }
        public virtual DbSet<t_account_company> t_account_company { get; set; }
        public virtual DbSet<t_account_fetch> t_account_fetch { get; set; }
        public virtual DbSet<t_account_loan> t_account_loan { get; set; }
        public virtual DbSet<t_account_lock_and_unlock> t_account_lock_and_unlock { get; set; }
        public virtual DbSet<t_account_patch> t_account_patch { get; set; }
        public virtual DbSet<t_account_transfer> t_account_transfer { get; set; }
        public virtual DbSet<t_salary_info> t_salary_info { get; set; }
    }
}
