//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralService.Core.Statistics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSsnapshotdeliveryprogress
    {
        public string session_token { get; set; }
        public int progress_token_hash { get; set; }
        public string progress_token { get; set; }
        public Nullable<System.DateTime> progress_timestamp { get; set; }
    }
}
