//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralService.Core.Statistics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_account_fetch
    {
        public int id { get; set; }
        public Nullable<int> a_id { get; set; }
        public Nullable<int> u_id { get; set; }
        public Nullable<int> bank { get; set; }
        public string account { get; set; }
        public Nullable<int> sign_item { get; set; }
        public Nullable<decimal> sign_money { get; set; }
        public Nullable<decimal> fact_money { get; set; }
        public Nullable<System.DateTime> sign_date { get; set; }
        public Nullable<System.DateTime> fact_date { get; set; }
        public Nullable<decimal> accrual { get; set; }
        public bool logout_tag { get; set; }
        public string remark { get; set; }
        public int sign_tag { get; set; }
        public string input_user { get; set; }
        public System.DateTime input_time { get; set; }
        public string sign_user { get; set; }
        public Nullable<System.DateTime> sign_time { get; set; }
        public string confirm_user { get; set; }
        public Nullable<System.DateTime> confirm_time { get; set; }
        public string test_u_name { get; set; }
        public string test_name { get; set; }
        public string test_id_card { get; set; }
        public string fgb_account { get; set; }
        public Nullable<System.DateTime> back_date { get; set; }
        public string tickit_remark { get; set; }
        public Nullable<int> out_tag { get; set; }
        public string number_id { get; set; }
        public string bank_card { get; set; }
        public string bank_u_name { get; set; }
        public Nullable<int> xml_id { get; set; }
        public Nullable<System.DateTime> end_month { get; set; }
        public Nullable<bool> over_area_tag { get; set; }
        public string over_area_unit_name { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
        public Nullable<int> area_code { get; set; }
        public Nullable<System.DateTime> begin_fetch_month { get; set; }
        public Nullable<System.DateTime> end_fetch_month { get; set; }
        public Nullable<decimal> after_money { get; set; }
        public string ZhiFuMiMa { get; set; }
        public string sign_opinion { get; set; }
        public string deposit_id { get; set; }
        public string deposit_name { get; set; }
        public Nullable<int> is_delete { get; set; }
        public Nullable<int> pre_account_status { get; set; }
        public string K3HandBillRefPiHao { get; set; }
        public Nullable<int> out_tag_accrual { get; set; }
        public string K3HandBillRefPiHao_accrual { get; set; }
        public Nullable<int> noNumberId { get; set; }
        public string loan_id { get; set; }
        public Nullable<int> notice_id { get; set; }
        public string notice_str { get; set; }
        public Nullable<bool> person_logout_first_tag { get; set; }
        public Nullable<int> open_bank { get; set; }
        public Nullable<System.DateTime> modify_time { get; set; }
        public string modify_user { get; set; }
        public Nullable<System.DateTime> sign_modify_time { get; set; }
        public string sign_modify_user { get; set; }
        public Nullable<bool> is_AutoFetch { get; set; }
    }
}
