//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralService.Core.Statistics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_account
    {
        public int Id { get; set; }
        public int u_id { get; set; }
        public string Id_Card { get; set; }
        public string Name { get; set; }
        public string Account { get; set; }
        public Nullable<System.DateTime> workdate { get; set; }
        public Nullable<System.DateTime> c_date { get; set; }
        public Nullable<int> Bank { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<decimal> u_money { get; set; }
        public Nullable<decimal> i_money { get; set; }
        public Nullable<decimal> Money { get; set; }
        public Nullable<decimal> accrual { get; set; }
        public Nullable<int> Status { get; set; }
        public string remark { get; set; }
        public int sign_tag { get; set; }
        public string input_user { get; set; }
        public System.DateTime input_time { get; set; }
        public string sign_user { get; set; }
        public Nullable<System.DateTime> sign_time { get; set; }
        public string number_id { get; set; }
        public string u_name { get; set; }
        public Nullable<decimal> money_backup { get; set; }
        public string fgb_account { get; set; }
        public string u_account { get; set; }
        public string tel { get; set; }
        public string mobile { get; set; }
        public string bank_card { get; set; }
        public Nullable<decimal> Render_Money { get; set; }
        public string bank_u_name { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<int> xml_id { get; set; }
        public Nullable<System.DateTime> fact_date { get; set; }
        public Nullable<double> bili { get; set; }
        public Nullable<bool> over_area_tag { get; set; }
        public Nullable<int> area_code { get; set; }
        public string corp_type { get; set; }
        public string corp_code { get; set; }
        public Nullable<decimal> u_bili { get; set; }
        public string ZhiFuMiMa { get; set; }
        public Nullable<decimal> i_bili { get; set; }
        public string account_backup { get; set; }
        public Nullable<int> noNumberId { get; set; }
        public Nullable<bool> is_loan_otherarea_tag { get; set; }
        public string render_city { get; set; }
        public Nullable<decimal> openMoney { get; set; }
        public Nullable<bool> is_id_card { get; set; }
        public Nullable<System.DateTime> modify_time { get; set; }
        public string modify_user { get; set; }
        public Nullable<System.DateTime> sign_modify_time { get; set; }
        public string sign_modify_user { get; set; }
        public string pwd { get; set; }
        public string EmpCode { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<decimal> NewBalance { get; set; }
        public string GLMen { get; set; }
        public string C18BitIdCard { get; set; }
    }
}
