//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralService.Core.Statistics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_account_transfer
    {
        public int id { get; set; }
        public Nullable<int> a_id { get; set; }
        public int out_unit_id { get; set; }
        public int in_unit_id { get; set; }
        public Nullable<int> out_bank { get; set; }
        public Nullable<int> in_bank { get; set; }
        public string out_account { get; set; }
        public string in_account { get; set; }
        public Nullable<decimal> balance { get; set; }
        public Nullable<System.DateTime> c_date { get; set; }
        public Nullable<System.DateTime> fact_date { get; set; }
        public Nullable<decimal> fact_money { get; set; }
        public Nullable<decimal> accrual { get; set; }
        public Nullable<System.DateTime> end_month { get; set; }
        public Nullable<int> tag { get; set; }
        public string remark { get; set; }
        public int sign_tag { get; set; }
        public string input_user { get; set; }
        public System.DateTime input_time { get; set; }
        public string sign_user { get; set; }
        public Nullable<System.DateTime> sign_time { get; set; }
        public string test_out_u_name { get; set; }
        public string test_name { get; set; }
        public string test_in_u_name { get; set; }
        public string test_id_card { get; set; }
        public Nullable<decimal> sign_money { get; set; }
        public Nullable<int> sign_confirm { get; set; }
        public string fgb_account { get; set; }
        public Nullable<System.DateTime> back_date { get; set; }
        public string tickit_remark { get; set; }
        public Nullable<int> out_tag { get; set; }
        public string number_id { get; set; }
        public Nullable<int> out_tag_out { get; set; }
        public Nullable<int> xml_in_id { get; set; }
        public Nullable<int> xml_out_id { get; set; }
        public Nullable<bool> To_Forign_Tag { get; set; }
        public Nullable<System.DateTime> out_fact_date { get; set; }
        public Nullable<System.DateTime> in_fact_date { get; set; }
        public Nullable<int> to_area { get; set; }
        public Nullable<bool> out_area_tag { get; set; }
        public Nullable<bool> over_area_tag { get; set; }
        public string over_area_unit_name { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
        public Nullable<int> area_code { get; set; }
        public Nullable<decimal> after_money { get; set; }
        public string ZhiFuMiMa { get; set; }
        public string in_unit_name { get; set; }
        public Nullable<int> is_delete { get; set; }
        public Nullable<int> pre_account_status { get; set; }
        public Nullable<decimal> in_after_money { get; set; }
        public string K3HandBillRefPiHao { get; set; }
        public string K3HandBillRefPiHao_out { get; set; }
        public Nullable<int> out_tag_accrual { get; set; }
        public string K3HandBillRefPiHao_accrual { get; set; }
        public Nullable<int> out_noNumberId { get; set; }
        public Nullable<int> in_noNumberId { get; set; }
        public Nullable<int> notice_id { get; set; }
        public string notice_str { get; set; }
        public Nullable<bool> is_combine_tag { get; set; }
        public Nullable<System.DateTime> modify_time { get; set; }
        public string modify_user { get; set; }
        public Nullable<System.DateTime> sign_modify_time { get; set; }
        public string sign_modify_user { get; set; }
        public Nullable<bool> is_BankChange_tag { get; set; }
        public string in_unit_account { get; set; }
        public Nullable<int> combine_id { get; set; }
        public Nullable<bool> sub_tag { get; set; }
        public Nullable<int> EmpID { get; set; }
        public System.Guid rowguid { get; set; }
        public string InACName { get; set; }
        public string InACAccount { get; set; }
        public Nullable<System.DateTime> delete_time { get; set; }
    }
}
