//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralService.Core.Statistics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_account_loan
    {
        public int id { get; set; }
        public Nullable<int> new_id { get; set; }
        public string male_name { get; set; }
        public Nullable<int> male_u_id { get; set; }
        public string male_u_name { get; set; }
        public string male_id_card { get; set; }
        public string female_name { get; set; }
        public Nullable<int> female_u_id { get; set; }
        public string female_u_name { get; set; }
        public string female_id_card { get; set; }
        public string pledge_address { get; set; }
        public Nullable<decimal> loan_target { get; set; }
        public Nullable<System.DateTime> b_date { get; set; }
        public Nullable<System.DateTime> e_date { get; set; }
        public Nullable<decimal> loan_money { get; set; }
        public Nullable<int> loan_term { get; set; }
        public Nullable<System.DateTime> a_date { get; set; }
        public Nullable<System.DateTime> sign_date { get; set; }
        public Nullable<System.DateTime> loan_date { get; set; }
        public Nullable<int> bank { get; set; }
        public string remark { get; set; }
        public Nullable<bool> loan_tag { get; set; }
        public Nullable<bool> return_tag { get; set; }
        public Nullable<int> sign_tag { get; set; }
        public string input_user { get; set; }
        public Nullable<System.DateTime> input_time { get; set; }
        public string sign_user { get; set; }
        public Nullable<System.DateTime> sign_time { get; set; }
        public Nullable<decimal> pici { get; set; }
        public string number_id { get; set; }
        public string fgb_account { get; set; }
        public Nullable<int> xml_id { get; set; }
        public bool AddLoan_Tag { get; set; }
        public Nullable<int> out_tag { get; set; }
        public string tickit_remark { get; set; }
        public Nullable<System.DateTime> return_date { get; set; }
        public Nullable<bool> over_area_tag { get; set; }
        public string over_area_unit_name { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
        public Nullable<int> area_code { get; set; }
        public System.DateTime cancel_date { get; set; }
        public byte repay_type { get; set; }
        public double monthly_rate { get; set; }
        public string account { get; set; }
        public string ShouFangUnit { get; set; }
        public string HomeAdress { get; set; }
        public Nullable<int> HomeType { get; set; }
        public Nullable<int> BuildQuality { get; set; }
        public Nullable<decimal> MianJi { get; set; }
        public string ContractNumber { get; set; }
        public Nullable<decimal> ToTalCost { get; set; }
        public Nullable<decimal> HandInCost { get; set; }
        public Nullable<decimal> HandInPercent { get; set; }
        public Nullable<bool> IsCombinateLoan { get; set; }
        public Nullable<decimal> BizLoanMoney { get; set; }
        public Nullable<int> BizLoanTerm { get; set; }
        public string GiveBackAccount { get; set; }
        public Nullable<int> DiYaCondition { get; set; }
        public string fore_confirm_user { get; set; }
        public Nullable<System.DateTime> fore_confirm_time { get; set; }
        public string final_confirm_user { get; set; }
        public Nullable<System.DateTime> final_confirm_time { get; set; }
        public string ZhiFuMiMa { get; set; }
        public Nullable<int> notice_id { get; set; }
        public string K3HandBillRefPiHao { get; set; }
        public Nullable<decimal> render_money { get; set; }
        public Nullable<int> noNumberID { get; set; }
        public Nullable<bool> is_net_data_tag { get; set; }
        public Nullable<System.DateTime> net_data_input_time { get; set; }
        public Nullable<System.DateTime> refuse_time { get; set; }
        public string refuse_user { get; set; }
        public string sign_opinion { get; set; }
        public Nullable<int> autofetch_tag { get; set; }
        public Nullable<System.DateTime> bank_b_date { get; set; }
        public Nullable<System.DateTime> bank_e_date { get; set; }
        public Nullable<System.DateTime> final_modify_time { get; set; }
        public string final_modify_user { get; set; }
        public Nullable<System.DateTime> fore_modify_time { get; set; }
        public string fore_modify_user { get; set; }
        public Nullable<System.DateTime> modify_time { get; set; }
        public string modify_user { get; set; }
        public Nullable<System.DateTime> sign_modify_time { get; set; }
        public string sign_modify_user { get; set; }
        public string BizLoanAccount { get; set; }
        public string bank_account_id { get; set; }
        public Nullable<bool> IsAutoFetch { get; set; }
        public Nullable<double> Year_Rate { get; set; }
        public string Receive_Name { get; set; }
        public string Receive_Account { get; set; }
        public Nullable<double> Rate_Flow { get; set; }
        public Nullable<int> NSign_tag { get; set; }
        public Nullable<System.DateTime> R_D { get; set; }
        public string R_U { get; set; }
        public Nullable<int> HouseNum { get; set; }
        public Nullable<int> RECBank { get; set; }
        public Nullable<decimal> ESTVakye { get; set; }
        public string GBAName { get; set; }
        public string notice_str { get; set; }
        public Nullable<bool> IsBankInput { get; set; }
        public Nullable<bool> BackToBank { get; set; }
        public string BankInputer { get; set; }
        public Nullable<System.DateTime> BankInputTime { get; set; }
        public string SF_Phone { get; set; }
        public string ZJJG { get; set; }
        public string ZJ_Phone { get; set; }
        public string JBR_Phone { get; set; }
        public Nullable<System.DateTime> LH_Date { get; set; }
        public Nullable<int> LH_H { get; set; }
        public string LH_Remark { get; set; }
        public Nullable<System.DateTime> LH_HTDate { get; set; }
    }
}
