//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralService.Core.Statistics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_account_company
    {
        public int id { get; set; }
        public string input_user { get; set; }
        public Nullable<System.DateTime> input_time { get; set; }
        public string modify_user { get; set; }
        public Nullable<System.DateTime> modify_time { get; set; }
        public string sign_user { get; set; }
        public Nullable<System.DateTime> sign_time { get; set; }
        public string sign_modify_user { get; set; }
        public Nullable<System.DateTime> sign_modify_time { get; set; }
        public Nullable<int> sign_tag { get; set; }
        public Nullable<int> status { get; set; }
        public string corp_name { get; set; }
        public Nullable<int> corp_quality { get; set; }
        public Nullable<int> corp_type { get; set; }
        public Nullable<System.DateTime> fund_c_date { get; set; }
        public string linkman { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string E_mail { get; set; }
        public string ip_address { get; set; }
        public string charge_dept { get; set; }
        public string income_source { get; set; }
        public Nullable<decimal> u_proportion { get; set; }
        public string og_code_id { get; set; }
        public string remark { get; set; }
        public string number_id { get; set; }
        public Nullable<int> table_code_id { get; set; }
        public Nullable<int> fund_type { get; set; }
        public Nullable<int> bank_for_unit { get; set; }
        public Nullable<System.DateTime> bank_open_date { get; set; }
        public string u_account { get; set; }
        public Nullable<int> area_code { get; set; }
        public string corp_code { get; set; }
        public string code { get; set; }
        public Nullable<bool> otherarea_tag { get; set; }
        public Nullable<int> organ_type { get; set; }
        public Nullable<int> economy_type { get; set; }
        public Nullable<int> industry_type { get; set; }
        public Nullable<int> belong_type { get; set; }
        public Nullable<System.DateTime> found_date { get; set; }
        public string charge_unit_name { get; set; }
        public string post_code { get; set; }
        public Nullable<System.DateTime> begin_render_date { get; set; }
        public string mobile_phone { get; set; }
        public string principal { get; set; }
        public string principal_phone { get; set; }
        public string principal_mobile_phone { get; set; }
        public string charge_unit_principal { get; set; }
        public string charge_unit_principal_phone { get; set; }
        public string approval_unit { get; set; }
        public string approval_document { get; set; }
        public string leagal_person_name { get; set; }
        public Nullable<int> leagal_person_cert_type { get; set; }
        public string leagal_person_cert_num { get; set; }
        public string leagal_person_phone { get; set; }
        public string leagal_person_mobile_phone { get; set; }
        public string leagal_person_email { get; set; }
        public string id_card_num { get; set; }
        public string callingupbuild_no { get; set; }
        public Nullable<int> is_cj { get; set; }
        public string Name { get; set; }
        public Nullable<int> DepID { get; set; }
        public string DWXZ { get; set; }
        public Nullable<int> Old_U_BiLi { get; set; }
    }
}
