//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralService.Core.Statistics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_salary_info
    {
        public int id { get; set; }
        public string name { get; set; }
        public int u_id { get; set; }
        public string u_name { get; set; }
        public string id_card { get; set; }
        public string account { get; set; }
        public Nullable<System.DateTime> work_date { get; set; }
        public decimal Salary { get; set; }
        public Nullable<double> bili { get; set; }
        public decimal render_money { get; set; }
        public System.DateTime adjust_date { get; set; }
        public Nullable<int> a_id { get; set; }
        public bool import_tag { get; set; }
        public Nullable<int> selected { get; set; }
        public string input_user { get; set; }
        public Nullable<System.DateTime> input_time { get; set; }
        public string import_user { get; set; }
        public Nullable<System.DateTime> import_time { get; set; }
        public int excel_row { get; set; }
        public Nullable<bool> over_area_tag { get; set; }
        public string over_area_unit_name { get; set; }
        public Nullable<decimal> u_bili { get; set; }
        public Nullable<int> is_delete { get; set; }
        public Nullable<decimal> i_bili { get; set; }
        public Nullable<bool> is_ration_adjust_tag { get; set; }
        public Nullable<decimal> pre_salary { get; set; }
        public Nullable<decimal> pre_render_money { get; set; }
        public Nullable<decimal> pre_u_bili { get; set; }
        public Nullable<decimal> pre_i_bili { get; set; }
        public Nullable<decimal> pre_u_money { get; set; }
        public Nullable<decimal> pre_i_money { get; set; }
        public Nullable<System.DateTime> modify_time { get; set; }
        public string modify_user { get; set; }
        public Nullable<bool> is_TransferAdjust_tag { get; set; }
        public string remark { get; set; }
        public Nullable<int> EmpID { get; set; }
        public System.Guid rowguid { get; set; }
        public string number_id { get; set; }
    }
}
